apps/budget/urls.py
from django.urls import path

from . import views

app_name = 'budget'
urlpatterns = [
    path('', views.index, name='budget'),
]

apps/cli/urls.py
from django.urls import path

from . import views

app_name = 'cli'
urlpatterns = [
    path('', views.cli, name='cli'),


]

apps/library/urls.py
from django.urls import path

from . import views

app_name = 'library'
urlpatterns = [
    path('submit/', views.submit, name='submit'), # /library/submit
    path('book/<int:book_id>/', views.book, name='book'), # /library/book/<book_id>
]

apps/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index')
]

apps/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='tasks')
]

pdatamana/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from apps import library, recipes
from pdatamana import settings

urlpatterns = [
    # Administration
    path('admin/', admin.site.urls),
    # Root addresses
    path('', include('django.contrib.auth.urls')),
    path('', include('apps.dashboard.urls')),
    # Budget App
    path('budget/', include('apps.budget.urls')),
    # Library App
    path('library/', include('apps.library.urls')),
    path('library/', library.views.index, name='library'),
    # Terminal App
    path('cli/', include('apps.cli.urls')),
    # Recipe App
    path('recipes/', include('apps.recipes.urls')),
    path('recipes/', recipes.views.index, name='recipes'),
    # Task App
    path('tasks/', include('apps.tasks.urls'))
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

apps/budget/models.py
from django.contrib.auth.models import User
from django.db import models


class IncomeType(models.Model):
    """
    Income types such as Advertising revenues from service X.
    """
    name = models.CharField(max_length=50, unique=True)


class Income(models.Model):
    """
    A model for incomes, everything is supposed to be uploaded.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateField()
    type = models.ForeignKey(IncomeType, on_delete=models.CASCADE, blank=True)


class ItemType(models.Model):
    name = models.CharField(max_length=50, unique=True)


class Item(models.Model):
    """
    Represents a single item, preferably added those which are commonly bought.
    """
    name = models.CharField(unique=True, max_length=50)
    type = models.ForeignKey(ItemType, on_delete=models.CASCADE, blank=True)


class Spending(models.Model):
    """
    We think that every spending is spent on an item, whether a physical product or a service.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)

apps/dashboard/models.py
from django.contrib.auth.models import User
from django.db import models


class TimeAllocation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    retire_date = models.DateField()

apps/library/models.py
from django.contrib.auth.models import User
from django.db import models


class Book(models.Model):
    """
    Tracking books the user wants to keep in mind.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    read = models.BooleanField(default=False)
    hasExercises = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Exercise(models.Model):
    """
    For tracking the exercise progress of a book.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    number = models.CharField(max_length=20)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.book.title + ' ' + self.number

apps/recipes/models.py
from django.db import models


class Meal(models.Model):
    """
    Describes the type of meals such as dinner and breakfast.
    """
    name = models.CharField(max_length=50)


class Recipe(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(Meal, on_delete=models.CASCADE)


class Ingredient(models.Model):
    name = models.CharField(max_length=50)


class Unit(models.Model):
    value = models.CharField(max_length=5)


class RecipeContains(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.IntegerField()
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    priority = models.IntegerField()


class Procedure(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    number = models.IntegerField()
    description = models.CharField(max_length=150)

apps/budget/views.py
from django.shortcuts import render, redirect

from apps.budget.models import Income, Spending
from lib.printer import format_currency


def index(request):
    user = request.user
    context = {
        'income': Income.objects.filter(user=user),
        'spending': Spending.objects.filter(user=user)
    }
    for x in context['income']:
        x.amount = format_currency(x.amount)

    for x in context['spending']:
        x.amount = format_currency(x.amount)

    return render(request, 'budget.html', context)

apps/dashboard/views.py
from datetime import datetime

from django.shortcuts import render, redirect


from apps.budget.methods import get_spending, get_income
from apps.dashboard.models import TimeAllocation
from apps.tasks.models import Task
from lib.printer import format_currency


def index(request):
    if request.user.is_authenticated:
        try:
            user = request.user
            time_allocation = TimeAllocation.objects.get(user=user.id)

            start_date = time_allocation.start_date
            retire_date = time_allocation.retire_date

            # Calculate Total Hours retire - start
            total_hours = (retire_date - start_date).days * 24

            # Calculate Hours Consumed.
            hours_consumed = (datetime.now().date() - start_date).days * 24
            hours_left = total_hours - hours_consumed

            # Transform to percentage.
            time_as_percentage = ((total_hours - hours_consumed) / total_hours) * 100

            # Calculate money spent this month.

            context = {
                'user': user,
                'hours_left': hours_left,
                'time_as_percentage': time_as_percentage,
                'spending': format_currency(get_spending(request)),
                'income': format_currency(get_income(request)),
                'tasks': Task.objects.filter(user=user).order_by('due_time')
            }
            return render(request, 'dashboard.html', context)
        except Exception as e:
            print(e)
            return redirect('settings')
    else:
        return redirect('login')


def settings(request):
    context = {}

    if request.method == 'POST':
        print(request.POST['start-date'])

        t = TimeAllocation(user=request.user, start_date=request.POST['start-date'], retire_date=request.POST['end-date'])
        t.save()
        context['message'] = 'saved'
    else:
        context['message'] = None

    return render(request, 'settings.html', context)

apps/library/views.py
from django.shortcuts import render, redirect

from apps.library.models import Book


def index(request):
    context = {'books':  Book.objects.filter(user=request.user)}

    return render(request, 'library.html', context)


def book(request, book_id):
    """
    Individual book page displaying the progress of its exercises if they exists.

    :param book_id:
    :param request:
    :return:
    """
    context = {
        'book': Book.objects.get(user=request.user, id=book_id)
    }

    return render(request, 'book.html', context)


def submit(request):
    record = Book(
        user=request.user,
        title=request.POST['title'],
        subtitle=request.POST['subtitle'],
        author=request.POST['author'],
        edition=request.POST['edition'],
        read=True if request.POST['read'] == 'on' else False
    )
    record.save()

    return redirect('library')

apps/recipes/views.py
from django.shortcuts import render

from apps.tasks.models import Task


def index(request):
    """
    This is the main view of tasks app.
    Everything should be visible on modifiable in this one page.
    """
    return render(request, 'recipes.html')

templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    {% block css %}{% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <title>{% block title %}Personal Data Manager{% endblock %}</title>
</head>

<body>
</body>
</html>

templates/base_private.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main.min.css' %}">
    {% block css %}{% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <title>{% block title %}Personal Data Manager{% endblock %}</title>
</head>

<body>
    {% if user.is_authenticated %}
    <nav id="top-navigation" role="navigation">
        <a id="brand" href="{% url 'index' %}">Datamana</a>
        <a id="budget" href="{% url 'budget:budget' %}">Budget</a>
        <a href="">Calendar</a>
        <a href="">Keys</a>
        <a id="library" href="{% url 'library' %}">Library</a>
        <a href="">Projects</a>
        <a id="recipes" href="{% url 'recipes' %}">Recipes</a>
        <a id="tasks" href="{% url 'tasks:tasks' %}">Tasks</a>
        <a id="sign-out" href="{% url 'logout' %}">Sign out</a>
    </nav>

    <div class="content">
        {% block main %}{% endblock %}
    </div>

    <!-- Command-line Interface -->
    <div id="cli">
        <button id="cli-toggler" onclick="toggle()">CLI</button>
        <div id="cli-inner">
            <p id="cli-output"></p>
            <form method="post" action="{% url 'cli:cli' %}">
                {% csrf_token %}
                <input type="text" placeholder="Command-line Interface" name="command" autocomplete="off">
            </form>
        </div>
    </div>

    <!-- Set the active link style.-->
    <script>
        document.getElementById("{% block link-id %}{% endblock %}").classList.add("active-link");
    </script>

    <script type="text/javascript" src="{% static 'js/cli.js' %}"></script>
    {% else %}
    <h1>Permission denied.</h1>
    {% endif %}
</body>
</html>

templates/budget.html
{% extends 'base.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/budget.css' %}">
{% endblock %}

{% block link-id %}budget{% endblock %}

{% block main %}
<!-- INCOME TABLE -->
<h1>Income</h1>
<table>
    <tr>
        <th class="date">Date</th>
        <th class="amount">Amount</th>
        <th class="category">Category</th>
        <th class="description">Description</th>
    </tr>
    {% for record in revenues %}
    <tr>
        <td>{{ record.date }}</td>
        <td>{{ record.amount }}</td>
        <td>{{ record.category.value }}</td>
        <td>{{ record.description }}</td>
    </tr>
    {% endfor %}
</table>

<!-- SPENDINGS TABLE -->
<h1>Spendings</h1>
<table>
    <tr>
        <th class="date">Date</th>
        <th class="amount">Amount</th>
        <th class="category">Category</th>
        <th class="description">Description</th>
    </tr>
    {% for record in spending %}
    <tr>
        <td>{{ record.date }}</td>
        <td>{{ record.amount }}</td>
        <td>{{ record.category.value }}</td>
        <td>{{ record.description }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard.css' %}">
{% endblock %}

{% block main %}
<!-- Time Until Retirement-->
<div class="progress-bar-outer">
    <div class="progress-bar-inner" style="width: {{ time_as_percentage }}%; text-align: center">
        Hours until retirement: {{ hours_left }}
    </div>
</div>

<p>Money spent (this month): {{ spending }} €</p>
<p>Money earned (this month): {{ earnings }} €</p>

<div>
    <div>
        <table>
            <tr>
                <th>Task</th>
                <th>Due Date</th>
            </tr>
        </table>
    </div>
    <div>

    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block main %}

{% endblock %}

templates/library.html
{% extends 'base.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/library.css' %}">
{% endblock %}

{% block link-id %}library{% endblock %}
{% block main %}
<table>
    <tr>
        <th class="title">Title</th>
        <th class="authors">Author(s)</th>
        <th>Edition</th>
        <th>Read</th>
    </tr>

    {% for book in books %}
    <tr>
        <td>{{ book.title }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.edition }}</td>
        <td>{{ book.read }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/recipes.html
<!-- MIT License
     Copyright (c) 2018 C. H. Lay -->
{% extends 'base_private.html' %}

{% block link-id %}recipes{% endblock %}

{% block main %}
<h1>Daily Meal Plan</h1>
<button type="button" class="bg-light-accent dark-shades">New Meal Plan</button>
{% endblock %}